//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGamePatcher.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoGamePatcher.Languages.en-GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Game Patcher Version:.
        /// </summary>
        internal static string ABOUT_AUTO_GAME_PATCHER_VERSION {
            get {
                return ResourceManager.GetString("ABOUT_AUTO_GAME_PATCHER_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the developer and the contributers:.
        /// </summary>
        internal static string ABOUT_DEVELOPER_AND_CONTRIBUTERS {
            get {
                return ResourceManager.GetString("ABOUT_DEVELOPER_AND_CONTRIBUTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software was made by Ethem Kurt, also known as &quot;BigETI&quot;
        ///under the General Public License v3.0..
        /// </summary>
        internal static string ABOUT_DEVELOPER_AND_CONTRIBUTERS_TEXT {
            get {
                return ResourceManager.GetString("ABOUT_DEVELOPER_AND_CONTRIBUTERS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string ABOUT_PROJECT {
            get {
                return ResourceManager.GetString("ABOUT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is hosted at GitHub.
        ///.
        /// </summary>
        internal static string ABOUT_PROJECT_TEXT {
            get {
                return ResourceManager.GetString("ABOUT_PROJECT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software:.
        /// </summary>
        internal static string ABOUT_THIS_SOFTWARE {
            get {
                return ResourceManager.GetString("ABOUT_THIS_SOFTWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software allows to patch games safely and temporarily.
        ///Many modifications require you to modify game binaries, which gets annoying over time.
        ///Bad mods tend to break game binaries and/or interfear wich each other.
        ///Mod developers have created tools do deal against that.
        ///In order to mod multiple games safely, you need multiple solutions
        ///also known as &quot;mod loaders&quot; to compensate that.
        ///This software is an answer to the modding community for
        ///reliably and simply patch any game content that is available [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABOUT_THIS_SOFTWARE_TEXT {
            get {
                return ResourceManager.GetString("ABOUT_THIS_SOFTWARE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations:.
        /// </summary>
        internal static string ABOUT_TRANSLATIONS {
            get {
                return ResourceManager.GetString("ABOUT_TRANSLATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - Ethem Kurt
        ///German - Ethem Kurt
        ///.
        /// </summary>
        internal static string ABOUT_TRANSLATIONS_TEXT {
            get {
                return ResourceManager.GetString("ABOUT_TRANSLATIONS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        internal static string ADD_DIRECTORY {
            get {
                return ResourceManager.GetString("ADD_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        internal static string ADD_FILE {
            get {
                return ResourceManager.GetString("ADD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        internal static string ADDITIONAL_INFO {
            get {
                return ResourceManager.GetString("ADDITIONAL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string APPEARANCE {
            get {
                return ResourceManager.GetString("APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a patch file entry name to continue.
        /// </summary>
        internal static string ASSIGN_PATCH_FILE_ENTRY_TO_CONTINUE {
            get {
                return ResourceManager.GetString("ASSIGN_PATCH_FILE_ENTRY_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Game Patcher.
        /// </summary>
        internal static string AUTO_GAME_PATCHER {
            get {
                return ResourceManager.GetString("AUTO_GAME_PATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string CONFIGURE {
            get {
                return ResourceManager.GetString("CONFIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Patch.
        /// </summary>
        internal static string CREATE_PATCH {
            get {
                return ResourceManager.GetString("CREATE_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this entry?.
        /// </summary>
        internal static string DELETE_ENTRY_QUESTION {
            get {
                return ResourceManager.GetString("DELETE_ENTRY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        internal static string DELETE_ENTRY_TITLE {
            get {
                return ResourceManager.GetString("DELETE_ENTRY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string DIRECTORIES {
            get {
                return ResourceManager.GetString("DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation &amp;&amp; Help.
        /// </summary>
        internal static string DOCUMENTATION_AND_HELP {
            get {
                return ResourceManager.GetString("DOCUMENTATION_AND_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patch.
        /// </summary>
        internal static string EDIT_PATCH {
            get {
                return ResourceManager.GetString("EDIT_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry already exists.
        /// </summary>
        internal static string ENTRY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ENTRY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string EXECUTABLE {
            get {
                return ResourceManager.GetString("EXECUTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string FILE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("FILE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files directory.
        /// </summary>
        internal static string GAME_FILES_DIRECTORY {
            get {
                return ResourceManager.GetString("GAME_FILES_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Patches.
        /// </summary>
        internal static string GAME_PATCHES {
            get {
                return ResourceManager.GetString("GAME_PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German/Deutsch.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to create?.
        /// </summary>
        internal static string HOW_TO_CREATE {
            get {
                return ResourceManager.GetString("HOW_TO_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to import?.
        /// </summary>
        internal static string HOW_TO_IMPORT {
            get {
                return ResourceManager.GetString("HOW_TO_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to share?.
        /// </summary>
        internal static string HOW_TO_SHARE {
            get {
                return ResourceManager.GetString("HOW_TO_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image link.
        /// </summary>
        internal static string IMAGE_LINK {
            get {
                return ResourceManager.GetString("IMAGE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image load error.
        /// </summary>
        internal static string IMAGE_LOAD_ERROR {
            get {
                return ResourceManager.GetString("IMAGE_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link is not referencing to a valid image.
        /// </summary>
        internal static string IMAGE_REFERENCE_ERROR {
            get {
                return ResourceManager.GetString("IMAGE_REFERENCE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Create Patch.
        /// </summary>
        internal static string IMPORT_CREATE_PATCH {
            get {
                return ResourceManager.GetString("IMPORT_CREATE_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Patch.
        /// </summary>
        internal static string IMPORT_PATCH {
            get {
                return ResourceManager.GetString("IMPORT_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string INTERNAL {
            get {
                return ResourceManager.GetString("INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string INVALID_FILE {
            get {
                return ResourceManager.GetString("INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less....
        /// </summary>
        internal static string LESS {
            get {
                return ResourceManager.GetString("LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        internal static string MANAGE_FILES {
            get {
                return ResourceManager.GetString("MANAGE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string MORE {
            get {
                return ResourceManager.GetString("MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch configuration.
        /// </summary>
        internal static string PATCH_CONFIGURATION {
            get {
                return ResourceManager.GetString("PATCH_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch file entry.
        /// </summary>
        internal static string PATCH_FILE_ENTRY {
            get {
                return ResourceManager.GetString("PATCH_FILE_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        internal static string PATCHES {
            get {
                return ResourceManager.GetString("PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Image.
        /// </summary>
        internal static string PREVIEW_IMAGE {
            get {
                return ResourceManager.GetString("PREVIEW_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file name.
        /// </summary>
        internal static string SELECT_FILE_NAME {
            get {
                return ResourceManager.GetString("SELECT_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file name to import..
        /// </summary>
        internal static string SELECT_FILE_NAME_TO_CONTINUE {
            get {
                return ResourceManager.GetString("SELECT_FILE_NAME_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to patch file.
        /// </summary>
        internal static string SELECT_FILES_TO_PATCH_FILE {
            get {
                return ResourceManager.GetString("SELECT_FILES_TO_PATCH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a style....
        /// </summary>
        internal static string SELECT_STYLE {
            get {
                return ResourceManager.GetString("SELECT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme....
        /// </summary>
        internal static string SELECT_THEME {
            get {
                return ResourceManager.GetString("SELECT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a patch file to import..
        /// </summary>
        internal static string SELECT_TO_IMPORT {
            get {
                return ResourceManager.GetString("SELECT_TO_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string STYLES {
            get {
                return ResourceManager.GetString("STYLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string THEMES {
            get {
                return ResourceManager.GetString("THEMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry already exists..
        /// </summary>
        internal static string THIS_ENTRY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("THIS_ENTRY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file already exists. Do you really want to overwrite it?.
        /// </summary>
        internal static string THIS_FILE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("THIS_FILE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not an &quot;Auto Game Patcher&quot; file..
        /// </summary>
        internal static string THIS_IS_NOT_AGP_FILE {
            get {
                return ResourceManager.GetString("THIS_IS_NOT_AGP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
    }
}
